# Generated by Django 5.2 on 2026-02-18 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Youth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full Name', max_length=200)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('civil_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Separated', 'Separated'), ('Live-in', 'Live-in')], max_length=20)),
                ('religion', models.CharField(blank=True, max_length=100)),
                ('purok', models.CharField(blank=True, max_length=100)),
                ('municipality', models.CharField(default='Manolo Fortich', max_length=100)),
                ('province', models.CharField(default='Bukidnon', max_length=100)),
                ('region', models.CharField(default='X', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('is_in_school', models.BooleanField(default=False, verbose_name='In School')),
                ('is_osy', models.BooleanField(default=False, verbose_name='Out of School Youth')),
                ('is_working_youth', models.BooleanField(default=False, verbose_name='Working Youth')),
                ('is_pwd', models.BooleanField(default=False, verbose_name='Person with Disability')),
                ('osy_willing_to_enroll', models.BooleanField(default=False, verbose_name='Willing to enroll?')),
                ('osy_program_type', models.CharField(blank=True, choices=[('Educational', 'Educational'), ('Vocational', 'Vocational')], max_length=50)),
                ('osy_reason_no_enroll', models.CharField(blank=True, max_length=200)),
                ('disability_type', models.CharField(blank=True, max_length=100)),
                ('has_specific_needs', models.BooleanField(default=False)),
                ('specific_needs_condition', models.CharField(blank=True, choices=[('SLD', 'Specific Learning Disability'), ('OHI', 'Other Hearing Impairment'), ('ASD', 'Autism Spectrum Disorder'), ('ED', 'Emotional Disturbance'), ('SLI', 'Speech Language Impairment'), ('VI', 'Visual Impairment'), ('Deafness', 'Deafness'), ('HI', 'Hearing Impairment'), ('DB', 'Deaf-Blind'), ('OI', 'Orthopedic Impairment'), ('ID', 'Intellectual Disability'), ('TBI', 'Traumatic Brain Injury'), ('MI', 'Multiple Intelligence')], max_length=100)),
                ('is_ip', models.BooleanField(default=False, verbose_name='Indigenous People (7 Tribes)')),
                ('tribe_name', models.CharField(blank=True, choices=[('Higaonon', 'Higaonon'), ('Tala-andig', 'Tala-andig'), ('Bukidnon', 'Bukidnon'), ('Umayamnon', 'Umayamnon'), ('Manobo', 'Manobo'), ('Matigsalug', 'Matigsalug'), ('Tigwahanon', 'Tigwahanon')], max_length=50)),
                ('is_muslim', models.BooleanField(default=False)),
                ('muslim_group', models.CharField(blank=True, choices=[('Tausug', 'Tausug'), ('Maranao', 'Maranao'), ('Maguindanao', 'Maguindanao'), ('Yakan', 'Yakan'), ('Sama-bajau', 'Sama-bajau')], max_length=50)),
                ('education_level', models.CharField(choices=[('Elementary', 'Elementary'), ('High School', 'High School'), ('Senior High', 'Senior High'), ('Open High', 'Open High'), ('ALS', 'Alternative Learning System'), ('College', 'College'), ('Masters', 'Masters'), ('Doctorate', 'Doctorate')], max_length=50)),
                ('course', models.CharField(blank=True, help_text='Course/Degree', max_length=150)),
                ('school_name', models.CharField(blank=True, help_text='School/University', max_length=150)),
                ('is_scholar', models.BooleanField(default=False)),
                ('scholarship_program', models.CharField(blank=True, max_length=100)),
                ('work_status', models.CharField(blank=True, max_length=50)),
                ('registered_voter_sk', models.BooleanField(default=False, verbose_name='Registered SK Voter')),
                ('registered_voter_national', models.BooleanField(default=False, verbose_name='Registered National Voter')),
                ('voted_last_sk', models.BooleanField(default=False, verbose_name='Voted Last SK Election')),
                ('attended_kk_assembly', models.BooleanField(default=False)),
                ('kk_assembly_times', models.IntegerField(default=0, help_text='How many times?')),
                ('kk_assembly_no_reason', models.CharField(blank=True, choices=[('No KK assembly', 'No KK assembly'), ('No interest', 'No interest')], max_length=100)),
                ('is_4ps', models.BooleanField(default=False, verbose_name='4Ps Beneficiary')),
                ('number_of_children', models.IntegerField(default=0)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.barangay')),
            ],
        ),
    ]
